//! Recycle Bin integration that rejects permanent deletion.
use cleaner_core::{RecycleError, Recycler};
use std::path::Path;

#[derive(Debug, Clone, Copy, Default)]
pub struct ShellRecycler;
impl Recycler for ShellRecycler {
    fn recycle(&self, paths: &[&Path]) -> Result<(), RecycleError> {
        #[cfg(windows)]
        {
            windows_recycle::recycle(paths)
        }
        #[cfg(not(windows))]
        {
            let _ = paths;
            Err(RecycleError::UnsupportedPlatform)
        }
    }
}

#[cfg(windows)]
#[expect(
    clippy::ref_as_ptr,
    clippy::inline_always,
    reason = "generated by the windows implement macro"
)]
mod windows_recycle {
    use super::{Path, RecycleError};
    use std::sync::{
        Arc,
        atomic::{AtomicBool, Ordering},
    };
    use windows::Win32::{
        Foundation::E_ABORT,
        System::Com::{
            CLSCTX_INPROC_SERVER, COINIT_APARTMENTTHREADED, CoCreateInstance, CoInitializeEx,
            CoUninitialize,
        },
        UI::Shell::{
            FILEOPERATION_FLAGS, FOF_NO_CONNECTED_ELEMENTS, FOF_NOCONFIRMATION, FOF_NOERRORUI,
            FOF_SILENT, FOFX_ADDUNDORECORD, FOFX_EARLYFAILURE, FOFX_RECYCLEONDELETE, FileOperation,
            IFileOperation, IFileOperationProgressSink, IFileOperationProgressSink_Impl,
            IShellItem, SHCreateItemFromParsingName, TSF_DELETE_RECYCLE_IF_POSSIBLE,
        },
    };
    use windows::core::{HRESULT, PCWSTR, Ref, Result, implement};
    struct Apartment;
    impl Drop for Apartment {
        fn drop(&mut self) {
            // SAFETY: initialized on this thread; every COM object is dropped first.
            unsafe { CoUninitialize() };
        }
    }
    #[implement(IFileOperationProgressSink)]
    struct RecycleOnly {
        completed: Arc<AtomicBool>,
    }
    // Reject a shell fallback to permanent deletion before the source is removed.
    fn require_recycling(flags: u32) -> Result<()> {
        if flags & TSF_DELETE_RECYCLE_IF_POSSIBLE.0.cast_unsigned() == 0 {
            return Err(E_ABORT.into());
        }
        Ok(())
    }
    impl IFileOperationProgressSink_Impl for RecycleOnly_Impl {
        fn StartOperations(&self) -> Result<()> {
            Ok(())
        }
        fn FinishOperations(&self, result: HRESULT) -> Result<()> {
            result.ok()
        }
        fn PreDeleteItem(&self, flags: u32, _item: Ref<IShellItem>) -> Result<()> {
            require_recycling(flags)
        }
        fn PostDeleteItem(
            &self,
            _flags: u32,
            _item: Ref<IShellItem>,
            result: HRESULT,
            recycled: Ref<IShellItem>,
        ) -> Result<()> {
            result.ok()?;
            if recycled.is_none() {
                return Err(E_ABORT.into());
            }
            self.completed.store(true, Ordering::Relaxed);
            Ok(())
        }
        fn PreRenameItem(&self, _flags: u32, _item: Ref<IShellItem>, _name: &PCWSTR) -> Result<()> {
            Ok(())
        }
        fn PostRenameItem(
            &self,
            _flags: u32,
            _item: Ref<IShellItem>,
            _name: &PCWSTR,
            _result: HRESULT,
            _new: Ref<IShellItem>,
        ) -> Result<()> {
            Ok(())
        }
        fn PreMoveItem(
            &self,
            _flags: u32,
            _item: Ref<IShellItem>,
            _dest: Ref<IShellItem>,
            _name: &PCWSTR,
        ) -> Result<()> {
            Ok(())
        }
        fn PostMoveItem(
            &self,
            _flags: u32,
            _item: Ref<IShellItem>,
            _dest: Ref<IShellItem>,
            _name: &PCWSTR,
            _result: HRESULT,
            _new: Ref<IShellItem>,
        ) -> Result<()> {
            Ok(())
        }
        fn PreCopyItem(
            &self,
            _flags: u32,
            _item: Ref<IShellItem>,
            _dest: Ref<IShellItem>,
            _name: &PCWSTR,
        ) -> Result<()> {
            Ok(())
        }
        fn PostCopyItem(
            &self,
            _flags: u32,
            _item: Ref<IShellItem>,
            _dest: Ref<IShellItem>,
            _name: &PCWSTR,
            _result: HRESULT,
            _new: Ref<IShellItem>,
        ) -> Result<()> {
            Ok(())
        }
        fn PreNewItem(&self, _flags: u32, _dest: Ref<IShellItem>, _name: &PCWSTR) -> Result<()> {
            Ok(())
        }
        fn PostNewItem(
            &self,
            _flags: u32,
            _dest: Ref<IShellItem>,
            _name: &PCWSTR,
            _template: &PCWSTR,
            _attributes: u32,
            _result: HRESULT,
            _new: Ref<IShellItem>,
        ) -> Result<()> {
            Ok(())
        }
        fn UpdateProgress(&self, _total: u32, _sofar: u32) -> Result<()> {
            Ok(())
        }
        fn ResetTimer(&self) -> Result<()> {
            Ok(())
        }
        fn PauseTimer(&self) -> Result<()> {
            Ok(())
        }
        fn ResumeTimer(&self) -> Result<()> {
            Ok(())
        }
    }
    pub(super) fn recycle(paths: &[&Path]) -> std::result::Result<(), RecycleError> {
        if paths.is_empty() {
            return Ok(());
        }
        // SAFETY: the worker owns this apartment for the duration of the call.
        unsafe { CoInitializeEx(None, COINIT_APARTMENTTHREADED) }
            .ok()
            .map_err(|error| shell_error(&error))?;
        let _apartment = Apartment;
        for path in paths {
            if !path.is_absolute() || path.as_os_str().is_empty() {
                return Err(RecycleError::UnsafePath(path.to_path_buf()));
            }
            recycle_one(path).map_err(|error| shell_error(&error))?;
        }
        Ok(())
    }
    fn shell_error(error: &windows::core::Error) -> RecycleError {
        if error.code() == E_ABORT {
            RecycleError::Aborted
        } else {
            RecycleError::ShellOperation(error.code().0)
        }
    }
    fn recycle_one(path: &Path) -> Result<()> {
        use std::os::windows::ffi::OsStrExt;
        let mut wide: Vec<u16> = path.as_os_str().encode_wide().collect();
        if wide.contains(&0) {
            return Err(E_ABORT.into());
        }
        wide.push(0);
        // SAFETY: COM is initialized and the class is the system file operator.
        let operation: IFileOperation =
            unsafe { CoCreateInstance(&FileOperation, None, CLSCTX_INPROC_SERVER) }?;
        let flags = FILEOPERATION_FLAGS(
            FOFX_RECYCLEONDELETE.0
                | FOFX_EARLYFAILURE.0
                | FOFX_ADDUNDORECORD.0
                | (FOF_NOCONFIRMATION.0
                    | FOF_NOERRORUI.0
                    | FOF_SILENT.0
                    | FOF_NO_CONNECTED_ELEMENTS.0),
        );
        // SAFETY: operation is live and flags contain documented values.
        unsafe { operation.SetOperationFlags(flags) }?;
        // SAFETY: wide is NUL-terminated and lives through the call.
        let item: IShellItem = unsafe { SHCreateItemFromParsingName(PCWSTR(wide.as_ptr()), None) }?;
        let completed = Arc::new(AtomicBool::new(false));
        let sink: IFileOperationProgressSink = RecycleOnly {
            completed: completed.clone(),
        }
        .into();
        // SAFETY: item and sink remain alive until synchronous completion.
        unsafe { operation.DeleteItem(&item, &sink) }?;
        // SAFETY: all queued interfaces remain alive.
        unsafe { operation.PerformOperations() }?;
        // SAFETY: operation remains valid after PerformOperations.
        if unsafe { operation.GetAnyOperationsAborted() }?.as_bool()
            || !completed.load(Ordering::Relaxed)
        {
            return Err(E_ABORT.into());
        }
        Ok(())
    }
    #[cfg(test)]
    mod tests {
        use super::*;
        #[test]
        fn permanent_deletion_is_rejected_before_execution() {
            assert!(require_recycling(0).is_err());
            assert!(require_recycling(0xffff & !128).is_err());
            assert!(require_recycling(128).is_ok());
        }
        #[test]
        fn shell_confirms_a_recycled_item() {
            let dir = tempfile::tempdir().unwrap();
            let file = dir.path().join("win-cleaner-recycle-test.tmp");
            std::fs::write(&file, b"recycle regression").unwrap();
            // Success requires PostDeleteItem to provide the item in the bin.
            recycle(&[&file]).unwrap();
            assert!(!file.exists());
        }
    }
}
#[cfg(all(test, not(windows)))]
mod tests {
    use super::*;
    #[test]
    fn recycler_reports_unsupported_platform() {
        assert!(matches!(
            ShellRecycler.recycle(&[Path::new("/anything")]),
            Err(RecycleError::UnsupportedPlatform)
        ));
    }
}
